-- Script unico: aggiunge TUTTE le colonne che potrebbero mancare su personaggi.
-- Usa IF NOT EXISTS quindi è sicuro da rieseguire più volte.

ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS classi JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS tiri_salvezza JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS competenze_abilita JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS maestrie_abilita JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS resistenze JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS immunita JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS slot_incantesimo JSONB DEFAULT '{}';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS risorse_classe JSONB DEFAULT '{}';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS dadi_vita_disponibili JSONB DEFAULT '{}';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS pv_attuali INTEGER;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS pv_temporanei INTEGER DEFAULT 0;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS background TEXT;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS concentrazione BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS accecato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS affascinato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS afferrato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS assordato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS avvelenato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS incapacitato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS invisibile BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS paralizzato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS pietrificato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS privo_di_sensi BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS prono BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS spaventato BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS stordito BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS trattenuto BOOLEAN DEFAULT FALSE;
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS esaustione INTEGER DEFAULT 0;
