ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS monete JSONB DEFAULT '{}';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS inventario JSONB DEFAULT '[]';
ALTER TABLE personaggi ADD COLUMN IF NOT EXISTS sintonia JSONB DEFAULT '[]';
